travis:
  secure:
    BINSTAR_TOKEN: HDyU2fPDkNnrNdpKoNF396SCzfY6FbCn3gLs0mYSzXHK+jHAdtlD6JfAFkDJWtCL5W3TUIg1NeYpGs3qdMjLhJbCmAnUqVB2UmxZt5F01tk5zsCCxnWJHuKweGqHz6KnmrRYEQtOcumP1cFiEasNJOAmX2zDRw+zCKPFyfi4qzJ8+RBovC+WVFRfOn2c868+jHK2agYGlJL14UDKyDL3Kv32YbkwH5Yza7+H4UkwSouHoWfrkgnB1eq6ddq7hoYjpdmWFIDG26nFGhdO40/2zPMiaiEBCcYF2qxYkzuZIeTK0sdRAsy4Ga++LhnDj96k6v7uaXDL+gP7+C9awt9XzXxNO4CS2V9FgGxjNZrPdg2K4P/g2wqicI2cQSibj7EP2DEfOxovSv34HPKfr8dP+kroxVScjMSg739/2ouN3vl5invr99O1zBm4wT7TzPaTRaTRWCBsWky0Sh6lT6felhtPXIKPNTHMg/vhy2c9ASjswotfvxrKOcbEsh88cxGukG3A0epVqeBQICXnvWOoehdxmrC1r6zhvd0Bn4orLLffxL03SAqCFTTB33R5BvNHb7TMmKW6ooLgEF72UJb6xFMvaQKu/+nKFpYqV4JpfMMNEm4tH2iICRapnbScC85hZ24tlRM97vEkChHp/IR0Lh913OIzYuUKpnAUmNCMVck=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
